config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'items#index'
  resources :items do
    collection do
      get 'search'
      get 'outcome'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
class Color < ActiveHash::Base
  self.data = [
    {id: 1, name: '--'},
    {id: 2, name: 'ホワイト'},
    {id: 3, name: 'ブラック'},
    {id: 4, name: 'グレー'},
    {id: 5, name: 'ブラウン'},
    {id: 6, name: 'ベージュ'},
    {id: 7, name: 'キャメル'},
    {id: 8, name: 'グリーン'},
    {id: 9, name: 'カーキ'},
    {id: 10, name: 'ネイビー'},
    {id: 11, name: 'ブルー'},
    {id: 12, name: 'パープル'},
    {id: 13, name: 'イエロー'},
    {id: 14, name: 'ピンク'},
    {id: 15, name: 'レッド'},
    {id: 16, name: 'ボルドー'},
    {id: 17, name: 'オレンジ'},
    {id: 18, name: 'シルバー'},
    {id: 19, name: 'ゴールド'},
    {id: 20, name: 'その他'}
  ]

  include ActiveHash::Associations
   has_many :items

end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_one_attached :image
  belongs_to :item_type
  belongs_to :season
  belongs_to :color

  with_options presence:true do
    validates :image
    validates :buy_day
  end

  with_options numericality: {other_than:1} do
    validates :item_type_id
    validates :season_id
    validates :color_id
  end

end

app/models/item_type.rb
class ItemType < ActiveHash::Base
  self.data = [
    { id: 1, name: '--'},
    { id: 2, name: 'トップス'},
    { id: 3, name: 'アウター'},
    { id: 4, name: 'インナー'},
    { id: 5, name: 'ボトムス'},
    { id: 6, name: 'セットアップ'},
    { id: 7, name: 'ワンピース'},
    { id: 8, name: 'バッグ'},
    { id: 9, name: 'シューズ'},
    { id: 10, name: '小物'},
    { id: 11, name: 'その他'}
  ]

  include ActiveHash::Associations
   has_many :items

end

app/models/season.rb
class Season < ActiveHash::Base
  self.data = [
    { id: 1, name:'--'},
    { id: 2, name:'春'},
    { id: 3, name:'夏'},
    { id: 4, name:'秋'},
    { id: 5, name:'冬'}
  ]

  include ActiveHash::Associations
   has_many :items

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :search_item, only: [:search, :outcome]


  def index
    @item = Item.all.order("created_at DESC")
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.create(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end


  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  def search
    @item = Item.all
  end

  def outcome
    @results = @p.result
  end


  private

  def item_params
    params.require(:item).permit(:item_type_id,:season_id,:buy_day,:color_id,:size_id,:price,:memo, :image)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def search_item
    @p = Item.ransack(params[:q])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<%= render "shared/header" %>

<div class ="item-new">
  <%= form_with model:@item, local: true do |f| %>
  <div class = "item-images">
    <div class = "item-new-img">
      服画像
    </div>
    <%= f.file_field :image, id:"item-image" %>
  </div>
  <div class = "item-types">
    <div class = "item-new-type">
      服の種類
    </div>
    <%= f.collection_select(:item_type_id, ItemType.all, :id, :name, {},{class:"item-type"}) %>
  </div> 
  <div class = "item-seasons">
    <div class = "item-new-season">
      季節
    </div>
    <%= f.collection_select(:season_id, Season.all, :id, :name, {},{class:"item-season"}) %> 
  </div>
  <div class = "item-colors">
    <div class = "item-new-color">
      色
    </div>
    <%= f.collection_select(:color_id,Color.all, :id, :name, {},{class:"item-color"}) %> 
  </div>
  <div class = "item-buy-days">
    <div class = "item-new-buy-day">
      購入日
    </div>
    <%= f.date_field :buy_day, class:"item-buy-day" %>
  </div>
  <div class = "item-prices">
    <div class = "item-new-price">
      値段
    </div>
    <div class ="item-price">
      <%= f.number_field :price,min:0, step:1000 %>円
    </div>
  </div>
  <div class = "item-memos">
    <div class = "item-new-memo">
      メモ
    </div>
    <%= f.text_area :memo, size:"30x5",class:"memo" %>
  </div>
  <div class = "item-btns">
    <%= f.submit "更新する",class: "item-btn" %>
    <%= link_to 'もどる', root_path, class: "back-btn" %>
  <% end %>
</div>

app/views/items/index.html.erb
<%= render "shared/header" %>

<div class = "item-index">
  <ul class='item-lists'>

    <% @item.each do |item| %>
    <li class = "list">

      <%= link_to item_path(item.id) do %>

        <%= image_tag item.image, class:"item-img" %>
      <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/items/new.html.erb
<%= render "shared/header" %>


<div class = "item-new">
  <div class ="item-new-form">
    <%= form_with model:@item, local: true do |f| %>
    <div class = "item-images">
      <div class = "item-new-img">
        服画像
      </div>
      <%= f.file_field :image, id:"item-image" %>
    </div>
    <div class = "item-types">
      <div class = "item-new-type">
        服の種類
      </div>
      <%= f.collection_select(:item_type_id, ItemType.all, :id, :name, {},{class:"item-type"}) %>
    </div> 
    <div class = "item-seasons">
      <div class = "item-new-season">
        季節
      </div>
      <%= f.collection_select(:season_id, Season.all, :id, :name, {},{class:"item-season"}) %> 
    </div>
    <div class = "item-colors">
      <div class = "item-new-color">
        色
      </div>
      <%= f.collection_select(:color_id,Color.all, :id, :name, {},{class:"item-color"}) %> 
    </div>
    <div class = "item-buy-days">
      <div class = "item-new-buy-day">
        購入日
      </div>
      <%= f.date_field :buy_day, class:"item-buy-day" %>
    </div>
    <div class = "item-prices">
      <div class = "item-new-price">
        値段
      </div>
      <div class ="item-price">
        <%= f.number_field :price,min:0, step:1000 %>円
      </div>
    </div>
    <div class = "item-memos">
      <div class = "item-new-memo">
        メモ
      </div>
      <%= f.text_area :memo, size:"30x5",class:"memo" %>
    </div>
    <div class = "item-btns">
      <%= f.submit "登録する",class: "item-btn" %>
      <%= link_to 'もどる', root_path, class: "back-btn" %>
    </div>
    <% end %>
  </div>
</div>

app/views/items/outcome.html.erb
<%= render "shared/header" %>

<h1 class= "search">
  検索結果
</h1>

<ul class='item-lists'>
  <% if @results.length !=0 %>
  <% @results.each do |item| %>
    <br>
      <li class='list'>
        <%= link_to item_path(item) do %>
        <div class='item-img-content'>
          <%= image_tag item.image, class: "item-img" %>
        <% end %>

        </div>
      <% end %>
  <% else %>
    該当する商品はありません
  <% end %>
  <br>
  
</ul>

app/views/items/search.html.erb
<%= render "shared/header" %>

<div class="items-search">
<h1 class = "search"> 検索</h1>
<%= search_form_for @p, url: outcome_items_path do |f| %>
  <div class = "item-show-search">
    <div class = "item-type-about">
      <%= f.label :item_type_id_eq, '服の種類',class:"item-type-name" %>
      <%= f.collection_select :item_type_id_eq, ItemType.all, :id, :name , {include_blank: "---"}, {class:"select-item-type"}  %>
    </div>
  <br>
    <div class = "season-about">
      <%= f.label :season_id_eq, '季節',class:"season-name" %>
      <%= f.collection_select :season_id_eq, Season.all, :id, :name , {include_blank: "---"}, {class:"select-season"} %>
    </div>
  <br>
    <div class = "color-about">
      <%= f.label :color_id_eq, '色',class:"color-name" %>
      <%= f.collection_select :color_id_eq, Color.all, :id, :name , {include_blank: "---"}, {class:"select-color"} %>
    </div>
  <br>

   <div class = price-ranges>
     <%= f.label :price_eq, '値段', class:"price-name" %>
     <div class = price-range>
      <%= f.number_field :price_gteq, min:0, size:30, step:1000,class:"price-range-gt" %>円
      <%= f.label :price_eq, ' 〜 ' %>
      <%= f.number_field :price_lteq, max:9999999, size:30, step:1000,class:"price-range-gt" %>円
     </div>
   </div>
  <br>
    <div class = "search-submits">
      <%= f.submit '検索', class:"search-submit" %>
    </div>
  </div>
<% end %>
</div>

app/views/items/show.html.erb
<%= render "shared/header" %>

<div class="item-show">
  <div class="item-box">
    <%= image_tag @item.image,class:"item-show-img" %>
    <div class = "item-show-button">
      <%= link_to "編集する",edit_item_path, class:"item-show-detail" %>
      <%= link_to "削除する",item_path, method: :delete, class:"item-show-delete" %>
    </div>


    <table class = "detail-table">
      <tbody>
        <tr>
          <th class = "detail-item">服の種類</th>
          <td class = "detail-value"><%= @item.item_type.name %></td>
        </tr>
        <tr>
          <th class = "detail-item">季節</th>
          <td class = "detail-value"><%= @item.season.name %></td>
        </tr>
        <tr>
          <th class = "detail-item">色</th>
          <td class = "detail-value"><%= @item.color.name %></td>
        </tr>
        <tr>
          <th class = "detail-item">購入日</th>
          <td class = "detail-value"><%= @item.buy_day %></td>
        </tr>
        <tr>
          <th class = "detail-item">値段</th>
          <td class = "detail-value"><%= @item.price %></td>
        </tr>
        <tr>
          <th class = "detail-item">メモ</th>
          <td class = "detail-value"><%= @item.memo %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClosetApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<header>
  <ul class = "header">
    <li><%= link_to image_tag("fashion.jpg",class:"closet-icon"),root_path %></li>
    <div class = "header-title">
    closet_app
    </div>
    <div class ="fashion-button">
      <li><%= link_to 'カテゴリー', search_items_path, class: "category-list" %></li>
      <li><%= link_to '服登録', new_item_path, class:"closet-new" %></li>
    </div>
  </ul>
</header>